plugins:
  - serverless-api-compression
  - serverless-s3-sync

custom:
  PRODUCT_NAME: "${env:PRODUCT_NAME}"
  STAGE: ${opt:stage, "dev"}
  STAGE_HOST_PREFIX:
    dev: "dev-"
    prod: ""
  REGION: "us-west-2"
  SERVICE_AND_STAGE: ${self:service}-${opt:stage}
  PRODUCT_AND_STAGE: ${self:custom.PRODUCT_NAME}-${opt:stage}

  NODE_ENV:
    dev: development
    prod: production
    contentEncoding:
      contentCompression: 100 # Minimum body size required for compression in bytes

service: "${self:custom.PRODUCT_NAME}-web"

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.STAGE}
  region: ${self:custom.REGION}
  apiName: ${self:custom.SERVICE_AND_STAGE}
  profile: ${opt:profile}
  memorySize: 512
  timeout: 30
  logRetentionInDays: 14
  environment:
    NODE_ENV: "${self:custom.NODE_ENV.${opt:stage, self:provider.stage}}"
    ENCRYPTION_SECRET: "${ssm:/${self:custom.SERVICE_AND_STAGE}/ENCRYPTION_SECRET~true}"
    JWT_SECRET: "${ssm:/${self:custom.PRODUCT_AND_STAGE}/JWT_SECRET~true}"

package:
  exclude:
    - readme.md
    - node_modules/@types/**
    - .git
    - .secrets*
    - "*.ts"
    - "*.tsx"
    - "*.d.ts"
    - "*.d.tsx"
    - "*.js.map"
    - cdn
    - scripts

functions:
  api:
    handler: "WebHandler.handler"
    events:
      - http: ANY /
      - http: "ANY {proxy+}"